import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { Toaster } from "@/components/ui/sonner";
import { ThemeProvider } from "@/components/ThemeProvider";
import NavigationComponent from "@/components/NavigationComponent";
import {MainContext} from "@/context/MainContext";

const montserrat = Montserrat({ 
  subsets: ["latin"], 
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"]
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen w-full flex flex-col",
          montserrat.className,
          {
            "debug-screens": process.env.NODE_ENV === "development"
          }
        )}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <MainContext>
            <div className="p-8 w-full">
              <NavigationComponent />
              {children}
            </div>
          </MainContext>
        </ThemeProvider>

        {/* main page */}
        
        <Toaster />
      </body>
    </html>
  );
}
